### PR TITLE
Personal tweaks

### PR DESCRIPTION
**Pull request by jefuwork**
Greetings. Thanks for this extension, I like it a lot, so decided to contribute a bit (thanks for open source tho). Made this pull request to show the differences and I want to know your opinion about the changes (most of them are personal preferences I guess, but anyway).

Open for discussion, can refactor some stuff you don't probably like. Feel free to close this pull request if you want.

Would be glad to hear code style tips, if there any.

---

<details>
  <summary>You can expand me to see :framed_picture:</summary>
  down below
</details>

---

## Bugs fixed:

- <details>
    <summary>History for the first loaded videos was incorrect: UI was rendered before we get history from storage (so you won't see any "watched" videos at the beginning) jefuwork@f5048e5bd31fc761b5ba82a92aa83b967ce0514c </summary>

  ```
  old
  ```

  

  ```
  new
  ```

  
  </details>

  Reason - loading from storage is an async function, so I wrapped it under a Promise object.

- <details>
    <summary>Videos loaded after you scroll down won't be marked as "watched" jefuwork@f5048e5bd31fc761b5ba82a92aa83b967ce0514c </summary>
  
  ```
  old
  ```

  

  ```
  new
  ```

  
  </details>

  Long story short (if I remember it correctly) the reason for this is that it's trying to change "not watched" button to "watched" one (when you load new videos in "hide watched" mode and then switch the toggle to "show watched" mode) - but "watched" videos weren't given any buttons on initialization.

  _Rebuild logic a bit for it to build UI only when history storage was loaded and create all buttons at the beginning._

  _**Resolves**_: https://github.com/OsaSoft/youtube-better-subscriptions/issues/65

### Minor fixes:

- <details>
    <summary>Fixed .subs-btn-settings SVG repeat (it appears when you hide any label or resize the window) jefuwork@48a569bd36a10fbdcce2b1056cce2cdbffba5579</summary>

  
  
  </details>

- <details>
    <summary>SVG icon fix jefuwork@408c9a7e16f3beeff16fd644a6a0bf43d89dbf58</summary>

  ```
  old
  ```

  

  ```
  new
  ```

  
  </details>

- <details>
    <summary>Open settings on a new page so you can see confirm dialog for storage clearing. (problem in Chrome). jefuwork@6f9ea46dfe4e52c314bc84f72c43af75959d768d</summary>
  
  
  </details>

  _Personally, I would add this in chrome version and ignore it in firefox._

## What's new:

- <details>
    <summary>Added support for channel videos page, added settings option to enable / disable it jefuwork@7ab3a29e14201d063e6d6bfab24058f6d40efa54</summary>
  
  
  </details>

  _**Resolves**_: https://github.com/OsaSoft/youtube-better-subscriptions/issues/59

- Made watched videos semitransparent and show "Mark as Watched" button on video hover only jefuwork@ec7378c1b93851115946bcd4719d31819e05abf7 jefuwork@681f4d37a3eab50517ad2e9db2adff72757ef5b5
  _for better visual clarity_
- Deleted hiding videos marked as watched by YouTube, cause I find it kind of unreliable jefuwork@f5048e5bd31fc761b5ba82a92aa83b967ce0514c
  _(will add in future if needed)._

### Settings:

- Enable / disable support for channel videos page (channel/\*/vids page). 
- Added option to keep the state of "Hide Watched" checkbox (while you are not reloading the page). jefuwork@ea4cf3acb24577b88b0c4bc437569ea184bb23ac
  _It allows you to go on video / channel / sub / etc pages and save the state of "Hide Watched" checkbox despite the default value (it will be applied on reload)._

- Added option to set video watched when you click on it. jefuwork@6bead761892b0c3b82a3693ef73aa9803c931e07
- Added option to show / hide Mark all as watched label. jefuwork@b02f4967823dd96a9d906153e7601d62b68dde74
- <details>
    <summary>Added option to stick UI to the right menu. jefuwork@e9dad1ac1c0b2d25da8239d42554438b73f932ee</summary>
  
  
  </details>

  _If you like minimalism or want to make ui more compact._

- <details>
    <summary>Minor page UI improvements. jefuwork@9ac73911decf3cd0d12067cf729ba2b4eeef96db</summary>
  
  
  </details>

###### Need to mention that:

- Old layout wasn't tested
- Currently new buttons will be created in "Hide watched" mode
  _Like it was before_

### CODE REVIEW

**Comment by OsaSoft** [comment]
This is absolutely awesome. Thanks a lot!
I currently have very little time to work on this extension, so every little helps and you did quite a bit!

Ill try to take a closer look as soon as I have at least a bit of time

**Comment by neiljdo** [comment]
Hi @jefuwork , I bit of a noobish question but I'm curious as to how you build the extension locally so you can try your own changes. I might want to try to add some feature (probably addressing #80) but I don't know where to start.

**Comment by jefuwork** [comment]
Hi @neiljdo. 
To install your fork in **chrome**: enable Developer Mode on **chrome://extensions**, сlick **Load Unpacked Extension** and select the directory with the downloaded project. 

In **Firefox**: open the **about:debugging** page, click **This Firefox** (in newer versions of Firefox), click **Load Temporary Add-on**, then select any file in your extension's directory.

**Comment by neiljdo** [comment]
Thank you very much @jefuwork !

**Comment by OsaSoft** [comment]
Sorry everyone for the long delay!
Im finally going through these PRs, yay! This will be the first one to go through. I might add a few changes, but overall looks good, thanks a lot @jefuwork !

Now for some github related tags...
Resolves #33 
Resolves #37 
Resolves #65

**Comment by OsaSoft** [comment]
Btw, this will be released in the next few days, depending on whether I will include some more features or not. Dont want to release right now, as its 0:30am and Im going to sleep, and releasing before being away for hours is never a great idea :smile:

**Pull request merged**
