### PR TITLE
Fix for shorts

### PR DESCRIPTION
**Pull request by Urhas**
Added if statement to getVideoIdFromUrl to handle shorts urls

### CODE REVIEW

**Review by Spurlos — APPROVED** [review]

**Review by Urhas — COMMENTED** [review]
If statement to get video id from new shorts url

**Comment by OsaSoft** [comment]
Im sorry, I wanted to switch to a master only system, since develop here is completely unnecessary, but for some reason, that closed this PR and wont let me reopen it with master as the new target branch... 🤦‍♂️ 
@Urhas can you please reopen the PR with master as target branch?
Sorry!

**Comment by OsaSoft** [comment]
nvm, i temporarily readded develop :D

**Comment by OsaSoft** [comment]
Resolves #105

**Comment by Urhas** [comment]
I can move this over to the master branch if that makes things easier?

**Comment by OsaSoft** [comment]
@Urhas already managed to merge to merge it by temporarily creating develop again 😅 thanks! I have a bit of time tonight so I might add a few more things in and do a new release of the extension

**Comment by Urhas** [comment]
No problem. @OsaSoft As a side note the update also makes the addon no longer work on a channels video tab. I haven't been able to figure out why though.

**Pull request merged**
