### PR TITLE
#147 fix hide button disappeared after YT update

### LINKED ISSUE #147: YT changed again? I am seeing all my watched vids
I am seeing all my watched vids with the red bar, and there's no longer a "mark watched" eye-con.

### PR DESCRIPTION
**Pull request by ericfrazer**
match new YT updated divs, ad links. fixes #147

### CODE REVIEW

**Comment by SSJ3Goku** [comment]
Ok so how do I apply this update to the extension? I've never done this before.

**Comment by ericfrazer** [comment]
@OsaSoft sure thing bud! When you get a chance, a tag/release to the ff/chrome extensions repos would be awesome - thank you!

**Comment by OsaSoft** [comment]
Yep, just pushed the artifact to mozilla and chrome (v0.17.4). Firefox
always rolls out first, Chrome might take a bit.

@ssj3goku your browser should update the extension automatically once the
new version is approved by mozilla/google

**Comment by ericfrazer** [comment]
❤️👍

**Pull request merged**
